### ISSUE TITLE
How does the program work?

### ISSUE THREAD

**Issue by xlj199** [nusneuromorphic/PCA-RECT#1]
Hello, thank you for sharing your work!
Can you specify the detailed running steps?

**Comment by nusneuromorphic** [comment]
Hi, sorry for the late reply. We have updated the README file with better instructions on how to run the scripts. Let us know if you run into any issues.

**Comment by xlj199** [comment]
> Hi, sorry for the late reply. We have updated the README file with better instructions on how to run the scripts. Let us know if you run into any issues.

Thank you very much for your reply. I have one more question.At your cue, I ran Event_context_DEMOuav_rmax7by7rect_FAST.m .(Windos10+matlabR2016b)
Error message:Unable to read the file 'testfiles_binTD4cl_CYnewobs'.
No such files or directories exist.I created a document named as testfiles_binTD4cl_CYnewobs.
It's the same error message.

**Comment by nusneuromorphic** [comment]
Hi, please make sure that the path to the N-SOD dataset is correct. Afterwards, please remove any .dat files that may have been created and try to launch again.

Please let me know if it works, thanks.

**Comment by xlj199** [comment]
> Hi, please make sure that the path to the N-SOD dataset is correct. Afterwards, please remove any .dat files that may have been created and try to launch again.
> Please let me know if it works, thanks.

There were no original mistakes, but there were new ones.
>Event_context_DEMOuav_rmax7by7rect_FAST.m (line 224)
> bins = sub2ind([options.numSpatialY(i), options.numSpatialX(i), numWords], ...get_imagehist (line 20) 
>Error message: Subscript out of range in sub2ind (line 43)
Thank you in advance.

**Comment by nusneuromorphic** [comment]
Hi, sorry for all these troubles.

I believe I had this same error before. It happens because there is a bin file in the N-SOD dataset that is too small and not of much use. I have removed this from the dataset, but you probably have downloaded it from before. 

Please delete the file "bg_hand4_train.bin" from the "Train/Background/" folder, and launch the script again. Please remember to delete any .dat files or folders that may have been created in previous runs.

Thanks.

**Comment by xlj199** [comment]
> Hi, sorry for all these troubles.
> I believe I had this same error before. It happens because there is a bin file in the N-SOD dataset that is too small and not of much use. I have removed this from the dataset, but you probably have downloaded it from before.
> Please delete the file "bg_hand4_train.bin" from the "Train/Background/" folder, and launch the script again. Please remember to delete any .dat files or folders that may have been created in previous runs.
> Thanks.

Thanks for your reply. Now it is running smoothly.
1.I want to know how to get the "*.bin" data.Is it the same as the example_data.mat(
Matlab_AER_vision_functions) data.
2.I have an eDVS(no DAVIS) at the moment.What platforms (Caer or Jaer) are available?
You can collect the data yourself(such as N-SOD Dataset).
Very thanks.

**Comment by nusneuromorphic** [comment]
Hi, we have in-house software to record the bin files from the DAVIS camera. Unfortunately, it does not support the eDVS. I am not aware of the best way to record from eDVS but I think you can do so with jAER. It does not have to be bin format though. Any format that can be imported to MATLAB to create a struct with the form (x, y, p, ts) would be just fine.
